# File created for use with "REST Client" extension for VisualStudioCode
# Name: REST Client
# Id: humao.rest-client
# Description: REST Client for Visual Studio Code
# Version: 0.25.1
# Publisher: Huachao Mao
# VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=humao.rest-client

### Create user 
POST https://localhost/user HTTP/1.1
Content-type: application/json
Accept: application/json

{
    "name": "nombre de prueba",
    "email": "prueba.0@prueba.com",
    "emailVerified": false
}


### Add role to user
POST https://localhost/user/29a6d31c-7375-433f-ac60-ccdcc580a071/role/ec2b464c-e917-49ec-ae84-f6a25c001cbd


### Login
GET https://localhost/login
